name: dbsqflite2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  date_format: ^1.0.9
  device_info: ^2.0.0
  dotted_border: null
  flutter:
    sdk: flutter
  flutter_local_notifications: ^5.0.0
  fluttertoast: ^7.1.1
  http: ^0.13.1
  intl: null
  path_provider: any
  provider: null
  rxdart: ^0.26.0
  sqflite: any
  workmanager: null
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/check.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
